
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author K00200540
 */
public class Assignment2 extends javax.swing.JFrame {

    /**
     * Creates new form Assignment2
     */
    public Assignment2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    LinkedQueue queue1 = new LinkedQueue();
    LinkedQueue queue2 = new LinkedQueue();
    LinkedQueue queue3 = new LinkedQueue();

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonQueue1 = new javax.swing.JButton();
        jButtonQueue2 = new javax.swing.JButton();
        jButtonQueue3 = new javax.swing.JButton();
        jTextFieldInsert = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDisplay = new javax.swing.JTextArea();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Linked queues");

        jButtonQueue1.setText("Queue 1");
        jButtonQueue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQueue1ActionPerformed(evt);
            }
        });

        jButtonQueue2.setText("Queue 2");
        jButtonQueue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQueue2ActionPerformed(evt);
            }
        });

        jButtonQueue3.setText("Queue 3");
        jButtonQueue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQueue3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter Text (IN CAPS)      :");

        jTextAreaDisplay.setColumns(20);
        jTextAreaDisplay.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDisplay);

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonQueue1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonQueue2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonQueue3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jTextFieldInsert))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonQueue1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonQueue2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonQueue3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExit))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonQueue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQueue1ActionPerformed
        if ("".equals(jTextFieldInsert.getText())) {
            jTextAreaDisplay.setText("Must enter something");
        } else {
            queue1.append(jTextFieldInsert.getText().toUpperCase());

            jTextAreaDisplay.setText(queue1.back() + " : added to Queue 1");
            jTextFieldInsert.setText("");
            jTextFieldInsert.requestFocus();
            System.out.println(queue1);
        }
    }//GEN-LAST:event_jButtonQueue1ActionPerformed

    private void jButtonQueue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQueue2ActionPerformed
        if ("".equals(jTextFieldInsert.getText())) {
            jTextAreaDisplay.setText("Must enter something");
        } else {
            queue2.append(jTextFieldInsert.getText().toUpperCase());

            jTextAreaDisplay.setText(queue2.back() + " : added to Queue 2 ");
            jTextFieldInsert.setText("");
            jTextFieldInsert.requestFocus();
            System.out.println(queue2);

        }
    }//GEN-LAST:event_jButtonQueue2ActionPerformed

    private void jButtonQueue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQueue3ActionPerformed
        String output = "";

        int compare;


        int total = queue1.size() + queue2.size();

        while (total > 0) {

            compare = queue1.front().toString().compareTo(queue2.front().toString());
            if (compare < 0) {
                //queue1's front is first alphabetical

                queue3.append("test");
                output += String.valueOf(queue3.back()) + "|";
                queue1.serve();

            } else if (compare > 0) {
                //queue2's front is first alphabetical
                queue3.append(queue2.front());
                output += String.valueOf(queue3.back()) + "|";
                queue2.serve();

            } else {
                //both queue's are the same alphabetical
                queue3.append(queue1.front());
                output += String.valueOf(queue3.back()) + "|";
                queue3.append(queue1.front());
                output += String.valueOf(queue3.back()) + "|";
                queue1.serve();
                queue2.serve();
            }

        }

        jTextAreaDisplay.setText(output);
        jTextFieldInsert.requestFocus();
    }//GEN-LAST:event_jButtonQueue3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment2().setVisible(true);
            }
        });
    }

//    public int compare(LinkedQueue o1, LinkedQueue o2) {
//        return o1.front().compareTo(o2.front());
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonQueue1;
    private javax.swing.JButton jButtonQueue2;
    private javax.swing.JButton jButtonQueue3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDisplay;
    private javax.swing.JTextField jTextFieldInsert;
    // End of variables declaration//GEN-END:variables
}
